Team 5: Added JSON saving and loading functionality
UQcsse3200/2024-studio-2 pull request #113
Opened 2024-08-25 09:48 UTC by lellis0406

Uses JSON to save and load game state/achievements. See wiki (https://github.com/UQcsse3200/2024-studio-2/wiki/Game-State-Saves) for functionality details.

Closes #15 .

2024-08-25 10:28 UTC, LucasRyall approved these changes
Functionally solid, small change with adding doc string to deleteJson().

2024-08-25 11:38 UTC, BaileyS03 commented on source/core/src/main/com/csse3200/game/files/FileLoader.java
> +  public static void deleteJson(String filename, Location location) {
Please add a doc string here.

2024-08-25 11:40 UTC, BaileyS03 requested changes
Code looks good, and there is good coverage. Please add the doc string where I added a comment.

2024-08-25 11:40 UTC, BaileyS03 commented on source/core/src/main/com/csse3200/game/files/FileLoader.java
> +  public static void deleteJson(String filename, Location location) {
Please add a doc string here

2024-08-25 11:40 UTC, mitsudz reviewed
One change requested - all looks good (not too much significant code changed since the last time I looked at this - mostly just rearranging and integrating into current codebase it looks like).

2024-08-25 11:40 UTC, mitsudz commented on .gitignore
> +*.json
Do not add .json to gitignore - a number of asset configurations are stored in .json files and may need to be modified (find another way to ignore loading/saving files)

2024-08-26 03:10 UTC, mitsudz approved these changes

2024-08-26 06:31 UTC, BaileyS03 approved these changes
Looks good thanks for fixing the doc strings!

2024-08-26 06:34 UTC, merged