4/ Implemented entity conversion
UQcsse3200/2024-studio-2 pull request #293
Opened 2024-09-11 12:23 UTC by shubhgupta2510

Closes #191 and implements the conversion of enemy entities to friendly entities once defeated. Currently, once the enemy is defeated, the game goes to a "Game Over" screen but the EntityConverter class works as expected and should show the enemy as a friendly once defeated.

2024-09-11 12:34 UTC, Jul-Wong reviewed
I think the item listener needs to be uncommented, and some commented out methods should probably be deleted if not used.

2024-09-11 15:08 UTC, owenrharding reviewed
Looks good, just merge with main and I'll approve

2024-09-11 15:08 UTC, owenrharding commented on source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
> +  public static List<Entity> enemies = null;
I wouldn't set it to null if you're going to set it to a new ArrayList in the initialiser anyways

2024-09-12 00:42 UTC, LucasRyall requested changes
Fatal Bug that needs to be resolved, on returning to the MainGameScreen enemies aren't properly disposed of, and cause the game to crash (unknown exact cause but replicatable by killing an enemy and then walking over their last pos/spawnpos).

2024-09-12 04:20 UTC, closed without merging