Inventory and item use accessible in Combat
UQcsse3200/2024-studio-2 pull request #432
Opened 2024-09-30 05:28 UTC by PHONGNGYUEN1

# Description

This branch includes functionality in the Combat screen item button i.e. toggling the inventory when triggered and ensuring the items use functionality can be accessed. Using the item will also be considered as a move in combat. Restrictions on using potions in certain game states have been applied, e.g., if a player was not in combat, they are restricted from using attack and defence and vice versa to speed potions. This also includes logic changes in TimedUsedItems as it is now a time use. If a player was in combat and used defence after combat is finished the effect will revert to the original player stats.

Fixes / Closes # (issue)
There is 3 features included  in the request 

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Unit testing was run to check the build and User testing of the game was conducted to ensure the quality and functionality of the newly added implementations were working

- [ ] Visual Testing of the dialogue update when a player attempts to use the item in non-appropriate areas
- [ ] Visual Testing of the item button when toggling off and on the button in combat
- [ ] Functionality testing when a player uses items in Combat

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-09-30 10:07 UTC, ChristianMario4 commented on source/core/src/main/com/csse3200/game/screens/CombatScreen.java
> +        .addComponent(new CombatButtonDisplay(oldScreen, oldScreenServices)); //manager.getPlayer()));
Do you need this comment??? Can it be removed?

2024-09-30 12:03 UTC, mitsudz requested changes
Requesting changes regarding poor modularity/duplicate code of inventory display for player/combat. Idk exactly how you want to rework it - but CombatInventoryDisplay is for the most part just a copy paste of PlayerInventoryDisplay. They should both be in the inventory component section, and one should inherit off the other (or they both inherit off a super class). Also, see main for changes to InventoryComponent & PlayerInventoryDisplay that are being overwritten unnecessarily here.
Please change all unnecessary info level logger messages to debug level. 
Other comments in code.

2024-10-01 23:19 UTC, mitsudz approved these changes

2024-10-01 23:31 UTC, BaileyS03 approved these changes
Gameplay seems appropriate as well as style. No new breaks which is always good.

It would be good to have an exit button on the items popup in sprint 4 during combat since it didn't seem intuitive to me to press items again since it was kind of hidden.

2024-10-02 02:15 UTC, merged