Update Entity Converting Tests to NPC Factory
UQcsse3200/2024-studio-2 pull request #472
Opened 2024-10-02 11:42 UTC by Jul-Wong

# Description
Adds tests to NPC factory and completes #457. Has no change on game functionality, only changing testing classes mainly

2024-10-03 03:31 UTC, theboah requested changes
Please resolve conflicts ready for merge then will recheck builds and runs. Tests look valid otherwise.

2024-10-03 04:15 UTC, theboah approved these changes

2024-10-04 12:49 UTC, mitsudz requested changes
Seems to be a lot of random changes to do with spacing that don't improve styling. Also a bunch of commented out tests which should either be removed or made to work. Please look through this pr yourself - there is also a error file you're trying to send to main, and an extra 2024-studio-2 directory which shouldn't be there. I'm also unsure why you're deleting the .github/pull_request_template.md file.

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/test/com/csse3200/game/minigames/maze/entities/factories/MazeNPCFactoryTest.java
> -@ExtendWith(GameExtension.class)
If you get rid of this the test won't actually run when building.

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/test/com/csse3200/game/minigames/maze/entities/factories/AnglerFishTest.java
> +
?

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/test/com/csse3200/game/minigames/maze/components/MazeTouchAttackComponentTest.java
> +
?

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/test/com/csse3200/game/minigames/maze/components/MazeCombatStatsComponentTest.java
> +
?

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
> +     */
Why is this test commented out? Please either make it work with the current game or remove it.

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
> +     * Tests that the friendly frog has a wait animation.
Why is this test commented out? Please either make it work with the current game or remove it.

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
> +//    @Test
Why is this test commented out? Please either make it work with the current game or remove it.

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/test/com/csse3200/game/entities/factories/NPCFactoryTest.java
> +//        for (String soundPath : testSoundPath) {
Why is this test commented out? Please either make it work with the current game or remove it.

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/main/com/csse3200/game/screens/MazeGameScreen.java
> +
?

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/main/com/csse3200/game/screens/MazeGameScreen.java
> -
?

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/main/com/csse3200/game/screens/EndMiniGameScreen.java
> +
?

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/main/com/csse3200/game/minigames/maze/entities/mazenpc/Jellyfish.java
> +
?

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/main/com/csse3200/game/minigames/maze/entities/mazenpc/FishEgg.java
> +
?

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/main/com/csse3200/game/minigames/maze/entities/MazePlayer.java
> +
?

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/main/com/csse3200/game/minigames/maze/components/MazeCombatStatsComponent.java
> +
?

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/main/com/csse3200/game/minigames/maze/areas/MazeGameArea.java
> +     * Playes backgroun music for the maze mini-game
?

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/main/com/csse3200/game/minigames/maze/areas/MazeGameArea.java
> +
?

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/main/com/csse3200/game/minigames/maze/areas/MazeGameArea.java
> +
?

2024-10-04 12:49 UTC, mitsudz commented on source/core/src/main/com/csse3200/game/minigames/maze/Maze.java
> +
?

2024-10-15 04:27 UTC, closed without merging