Fix SonarCloud Warning for area package
UQcsse3200/2024-studio-2 pull request #570
Opened 2024-10-10 12:02 UTC by Howard-12

# Description

Clean up code to meet SonarCloud requirements and refactor code when necessary. Functionality remains the same. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
The game run without crashes, and terrains are generated as expected : )

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-10-10 21:17 UTC, mitsudz requested changes
A few small styling changes requested.

2024-10-10 21:17 UTC, mitsudz commented on source/core/src/main/com/csse3200/game/areas/MapHandler.java
>    public static boolean getUnlockedOcean() {
Can some of these functions just be combined and take in an enum, e.g. getUnlocked(MapType type)?

2024-10-10 21:17 UTC, mitsudz commented on source/core/src/main/com/csse3200/game/areas/terrain/TerrainChunk.java
> +      case MapType.FOREST -> totalTiles = terrainResource.getForestSize();
I'm not sure this change is an improvement - it requires a function for each map type which is pointless considering they do the same thing.

2024-10-10 21:17 UTC, mitsudz commented on source/core/src/main/com/csse3200/game/areas/terrain/TerrainResource.java
> +    public int getForestSize() {
I think it's reasonable to combine these four functions to just take in an enum for the tile/map type

2024-10-11 02:39 UTC, mitsudz approved these changes
Looks good!

2024-10-11 02:59 UTC, tompreston1 approved these changes

2024-10-11 03:10 UTC, PHONGNGYUEN1 approved these changes
Looks pretty good. approved

2024-10-11 03:17 UTC, merged