1/player branch
UQcsse3200/2024-studio-2 pull request #71
Opened 2024-08-16 17:22 UTC by shaivikaaaa

This pull request introduces the implementation of the Animal Selection Screen layout, which appears when the player clicks on the "Start" button. The focus of this task was on designing and implementing the visual layout with placeholder icons for the animals, ensuring a smooth transition from the main menu to this screen.

2024-08-16 23:08 UTC, mitsudz requested changes
See comments. There are a number of changes requested, split into 2 main parts:
1) Refactoring of method show in AnimalSelectionScreen (it is too long with too much code duplication)
2) Changing AnimalSelectionScreen to be managed by GdxGame properly - not the ServiceLocator (the ServiceLocator doesn't need to see the game, the current changes violate the principles of the architecture that is already present).

2024-08-16 23:08 UTC, mitsudz commented on source/core/src/main/com/csse3200/game/screens/AnimalSelectionScreen.java
> +        this.game = game;
Add logging here.

2024-08-16 23:08 UTC, mitsudz commented on source/core/src/main/com/csse3200/game/screens/AnimalSelectionScreen.java
> +        this.game = game;
Should this function be registering services here? Ie the input service to handle button clicks (I'm not sure if you should use that or the way you have done it is better - someone else can check that).

2024-08-16 23:08 UTC, mitsudz commented on source/core/src/main/com/csse3200/game/GdxGame.java
> +    ServiceLocator.registerGame(this);
Remove this - the game is not a service. See comments in MainMenuDisplay and ServiceLocator for more details.

2024-08-17 01:32 UTC, shaivikaaaa commented on source/core/src/main/com/csse3200/game/services/ServiceLocator.java
> +import com.csse3200.game.GdxGame;
did not get the reason for this

2024-08-17 08:03 UTC, lellis0406 requested changes
Please see comments for requested changes/clarification.

2024-08-18 03:53 UTC, closed without merging